/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoaula.view;

import br.com.projetoaula.controller.Conexao;
import br.com.projetoaula.controller.UsuarioDAO;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Eduardo
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    Connection con;
    Conexao conexao = new Conexao();
    public JFLogin() {
        initComponents();
        con = conexao.conector();
        conexao.desconector(con);
        try{
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            System.out.println("erro");
        }
        
        try{
            con = conexao.conector();
            if(con != null){
                lblStatus2.setText("Online");
                lblStatus2.setForeground(Color.green);
                conexao.desconector(con);
            }else{
                lblStatus2.setText("Offline");
                lblStatus2.setForeground(Color.red);
                conexao.desconector(con);
            }
        }catch(Exception e){
            System.out.println("Erro: "+e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        btn_signin = new javax.swing.JButton();
        txt_user = new javax.swing.JLabel();
        txt_password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de Acesso - Sistema de Venda de Cervejas");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        btn_signin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduardo\\Documents\\NetBeansProjects\\ProjetoAula\\icones\\botao_login.png")); // NOI18N
        btn_signin.setText("Acessar");
        btn_signin.setInheritsPopupMenu(true);
        btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signinActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 130, 50));

        txt_user.setText("Usuário");
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        txt_password.setText("Senha");
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduardo\\Documents\\NetBeansProjects\\ProjetoAula\\icones\\form_login.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblStatus1.setText("Status do Banco de Dados:");
        getContentPane().add(lblStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        lblStatus2.setText("jLabel1");
        getContentPane().add(lblStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signinActionPerformed
        // TODO add your handling code here:
        UsuarioDAO us = new UsuarioDAO();
        if(us.Access(jTextField1, jPasswordField1)){
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_signinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    
        System.out.println(System.getProperty("user.dir")+"\\src");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel txt_password;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
